import { UserProfile } from "@/lib/user-types";

export const dummyData: UserProfile = {
  ecommerceInfo: {
    amazonStore: "https://www.amazon.com/s?k=profile-store",
    ebay: "https://www.ebay.com/str/profilestore",
    shopee: "https://shopee.com/profile-store",
    shopifyStore: "https://store.shopify.com/profile-store",
    lazada: "https://www.lazada.com.ph/shop/profile-store",
    etsy: "https://www.etsy.com/shop/profilestore",
  },
  additionalInfo: {
    fileSharing: "https://drive.google.com/drive/folders/12345",
    blog: "https://myblog.com",
    personal: {
      button_style: "rounded",
      profile_image:
        "https://e7.pngegg.com/pngimages/799/987/png-clipart-computer-icons-avatar-icon-design-avatar-heroes-computer-wallpaper-thumbnail.png",
      font_style: "Arial",
      font_size: 14,
      font_family: 'Roboto',
      theme: 'light',
      description:
        "Experienced software developer specializing in full-stack development.",
      background_image:
        "https://png.pngtree.com/thumb_back/fh260/background/20230408/pngtree-rainbow-curves-abstract-colorful-background-image_2164067.jpg",
      designation: "Software Developer",
      fullname: "Fahad",
    },
    resume: "https://www.example.com/resume.pdf",
    customLanding: "https://www.example.com/landing",
    event: "Upcoming tech conference in 2024",
  },
  paymentInfo: {
    gCash: "+639XXXXXXXXX",
    payoneer: "user.payoneer@domain.com",
    paypal: "user.paypal@domain.com",
    venmo: "@username",
    wise: "user@wise.com",
    cryptocurrency: "0x1234abcD1234fghIJKLmnopQRSTuvWXYZ5678",
    stripe: "user_stripe_account_id",
  },
  contactInfo: {
    skype: "live:username_skype",
    zoom: "https://zoom.us/j/1234567890",
    whatsapp: "+639XXXXXXXXX",
    calender: "https://calendar.google.com/calendar/xyz",
    googleMeet: "https://meet.google.com/abc-xyz-123",
    phoneNumber: "+639XXXXXXXXX",
    maplink: "https://www.google.com/maps/place/123+Street+Name",
    email: "user.email@example.com",
    physicalAddress: "1234 Example St, City, Country",
    telegram: "@username_telegram",
  },
  socialMediaInfo: {
    pinterest: "https://www.pinterest.com/userprofile",
    youtube: "https://www.youtube.com/c/userprofile",
    snapchat: "https://www.snapchat.com/add/username",
    twitter: "https://twitter.com/userprofile",
    upwork: "https://www.upwork.com/freelancers/~userprofile",
    appleMusic: "https://music.apple.com/us/artist/username/12345",
    amazon: "https://www.amazon.com/author/userprofile",
    facebook: "https://www.facebook.com/userprofile",
    substack: "https://userprofile.substack.com",
    instagram: "https://www.instagram.com/userprofile",
    spotify: "https://open.spotify.com/artist/userprofile",
    soundCloud: "https://soundcloud.com/userprofile",
    medium: "https://medium.com/@userprofile",
    dribble: "https://dribbble.com/userprofile",
    fiver: "https://www.fiverr.com/userprofile",
    github: "https://github.com/userprofile",
    linkedin: "https://www.linkedin.com/in/userprofile",
    behance: "https://www.behance.net/userprofile",
    tiktok: "https://www.tiktok.com/@userprofile",
    freelancer: "https://www.freelancer.com/u/userprofile",
  },
};
